### ISSUE TITLE
EPIPE Error on node v0.12

### ISSUE THREAD

**Issue by kuddl** [cbarrick/gulp-run#29]
Hi, 
there is an error, when I run this in node v0.12 or io.js 1.6.

it works, when I run it with node 0.10

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:766:14)
```

**Comment by tengyifei** [comment]
+1. Also having this issue. My workaround was (if you want to ignore all outputs):
```js
var runObj = run(<command>, { verbosity: 0 });
var oldTransform = runObj._transform;
// Hijack the original _transform function and swap out the stream
runObj._transform = function(_, enc, cb) {
  // have to manually call the task callback since we don't have the stream
  oldTransform('', enc, callback);    // callback belongs to gulp task
};
// Pipe into runObj
```

**Comment by blindmelon** [comment]
+1 Any word on this, it is a pretty major issue.

**Comment by MrBoolean** [comment]
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:766:14)
```

The same error occurs on travis-ci. To figure out whats going on, it is necessary to create a test case. This test case should isolate the problem. May one of u guys already have written such a test case?!
